### PR TITLE
Workflow Update + CAS Auth Refactor

### PR DESCRIPTION
**Pull request by builtbywill**

### CODE REVIEW

**Comment by gavin-brown** [comment]
In Radar, we're doing `import { sagas as authSagas, apis as authApis, getOauthToken } from 'studiokit-auth-js'
`

Will the changes to `api.js` affect that?

**Comment by builtbywill** [comment]
@gavin-brown I did change some `actions.js` and `apis.js` keys, so yeah that would need to be updated in Radar.

**Comment by gavin-brown** [comment]
Would the import process change as well? Or would you still be able to do `import {apis} from 'studiokit-auth-js'`

**Comment by builtbywill** [comment]
@gavin-brown No I didn't change anything other than the names, import should be the same.

**Comment by gavin-brown** [comment]
General comment. Pointing to a specific branch, i.e. `"studiokit-auth-js": "https://github.com/purdue-tlt/studiokit-auth-js.git#develop",` no longer works because of the removal of lib. I'm guessing, but don't know that it's because of `"main": "lib/index.js"` 

Unless I'm doing it wrong, which there's a solid chance of

**Comment by builtbywill** [comment]
@gavin-brown yeah that's right, the lib folder is not in the repo, but will be published to `npm`. if you load directly from a git url you will have to build the project. i think you can just open the node_modules/studiokit-auth-js folder and run `yarn build`

**Comment by gavin-brown** [comment]
Alright sweet, testing it now

I didn't get any import errors. So last question, is headless CAS now CAS V1 or CAS proxy?

**Comment by builtbywill** [comment]
@gavin-brown headless CAS => CAS proxy

**Pull request closed without merging**
